/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1styrGroupB
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Splash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Percentage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MyProgress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        Percentage.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Percentage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Percentage.setText("%");
        getContentPane().add(Percentage);
        Percentage.setBounds(150, 270, 160, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\1styrGroupB\\Desktop\\Javajan\\rsz_4j&r_appliances.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 450, 370);

        MyProgress.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(MyProgress);
        MyProgress.setBounds(0, 350, 440, 20);

        setSize(new java.awt.Dimension(440, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
         Splash MyLoadingPage = new Splash();
        MyLoadingPage.setVisible(true);
        try{
            for(int i=0;i<=100;i++)
            {
                Thread.sleep(40);
                MyLoadingPage.MyProgress.setValue(i);
                MyLoadingPage.Percentage.setText(Integer.toString(i)+("%"));
        }
        }catch(Exception e)
        {
                    
        }
        new LoginForm().setVisible(true);
        MyLoadingPage.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar MyProgress;
    private javax.swing.JLabel Percentage;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
